name: KCGI-Community

build:
  commands:
    - apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev
    - apt-get install -y php-gd

web:
  webserver: "nginx"
  document_root: "public"
